In [16]:
import pandas as pd
import numpy as np 

# Settings seed for reproductibility 
np.random.seed(42)

#Generating  1,000 rows of data
data= {
    'Patient_ID': range(101,1101),
       'Name': [f"Patient_{i}" for i in range(1000)],
       'Age':np.random.randint(-5,110, size =1000), #Includes messy data (negative age) 
       'Gender': np.random.choice (['Male', 'M', 'female', 'Female', 'None'], size=1000),
       'Diagnosis': np.random.choice (['Heart attack','Diabetes', 'Flu','Stroke'], size=1000),
       'Treatment_Cost': np.random.uniform(500, 10000, size=1000),
       'Readmitted': np.random.choice(['Yes', 'No'], size=1000, p=[0.3, 0.7])
       }
df = pd.DataFrame(data)

#Export to CSV for our "Data Managment" records
df.to_csv('healthcare_raw_data.csv', index=False)
print("Success! 'healthcare_raw_data.csv' with 1000 rows is ready.")

Success! 'healthcare_raw_data.csv' with 1000 rows is ready.

In [17]:
df.head()

   Patient_ID       Name  Age  Gender     Diagnosis  Treatment_Cost Readmitted
0         101  Patient_0   97  female        Stroke     6733.537458        Yes
1         102  Patient_1   46  female           Flu     2185.573310         No
2         103  Patient_2   87       M  Heart attack     5677.755730         No
3         104  Patient_3    9  Female      Diabetes     9854.362525         No
4         105  Patient_4  101    Male        Stroke     9405.186632         No

In [18]:
# 1. Round the cost to 2 decimal places
df['Treatment_Cost'] = df['Treatment_Cost'].round(2)

# 2. Fix the Gender mess (Standardizing)
# map the 'bad' names to 'good' names
gender_map = {'M': 'Male', 'female': 'Female', 'Male': 'Male', 'Female': 'Female'}
df['Gender'] = df['Gender'].map(gender_map).fillna('Others')

# 3. Fix the Age (Remove negative ages)
# "Only keep rows where age is 0 or older"
df = df[df['Age'] >= 0]

# 4. Drop the Name column (since it's not useful)
df = df.drop(columns=['Name'])

# Now let's see the clean version
df.head()

   Patient_ID  Age  Gender     Diagnosis  Treatment_Cost Readmitted
0         101   97  Female        Stroke         6733.54        Yes
1         102   46  Female           Flu         2185.57         No
2         103   87    Male  Heart attack         5677.76         No
3         104    9  Female      Diabetes         9854.36         No
4         105  101    Male        Stroke         9405.19         No

In [19]:
df.head()

   Patient_ID  Age  Gender     Diagnosis  Treatment_Cost Readmitted
0         101   97  Female        Stroke         6733.54        Yes
1         102   46  Female           Flu         2185.57         No
2         103   87    Male  Heart attack         5677.76         No
3         104    9  Female      Diabetes         9854.36         No
4         105  101    Male        Stroke         9405.19         No

In [20]:
df.tail()

     Patient_ID  Age  Gender Diagnosis  Treatment_Cost Readmitted
995        1096   92    Male  Diabetes         2598.10         No
996        1097   32  Female    Stroke          869.83         No
997        1098   44  Female  Diabetes          842.18         No
998        1099   92    Male       Flu         2164.61         No
999        1100   76  Others       Flu         8734.32         No

In [21]:
df.info

<bound method DataFrame.info of      Patient_ID  Age  Gender     Diagnosis  Treatment_Cost Readmitted
0           101   97  Female        Stroke         6733.54        Yes
1           102   46  Female           Flu         2185.57         No
2           103   87    Male  Heart attack         5677.76         No
3           104    9  Female      Diabetes         9854.36         No
4           105  101    Male        Stroke         9405.19         No
..          ...  ...     ...           ...             ...        ...
995        1096   92    Male      Diabetes         2598.10         No
996        1097   32  Female        Stroke          869.83         No
997        1098   44  Female      Diabetes          842.18         No
998        1099   92    Male           Flu         2164.61         No
999        1100   76  Others           Flu         8734.32         No

[947 rows x 6 columns]>

In [22]:
df.value_counts()

Patient_ID  Age  Gender  Diagnosis     Treatment_Cost  Readmitted
101         97   Female  Stroke        6733.54         Yes           1
102         46   Female  Flu           2185.57         No            1
103         87   Male    Heart attack  5677.76         No            1
104         9    Female  Diabetes      9854.36         No            1
105         101  Male    Stroke        9405.19         No            1
                                                                    ..
1096        92   Male    Diabetes      2598.10         No            1
1097        32   Female  Stroke        869.83          No            1
1098        44   Female  Diabetes      842.18          No            1
1099        92   Male    Flu           2164.61         No            1
1100        76   Others  Flu           8734.32         No            1
Name: count, Length: 947, dtype: int64

In [23]:
df.to_csv('cleaned_healthcare_data.csv',index=False)
print("Clean CSV saved! Ready for SQL import.")

Clean CSV saved! Ready for SQL import.